### ISSUE TITLE
Wanted：Could team of Aliyunpan take advices from you for product evolvement?

### ISSUE THREAD

**Issue by skorver** [liupan1890/aliyunpan#43]
email:yiyi.yp@alibaba-inc.com

**Comment by liupan1890** [comment]
十分抱歉，我的英语并不好
1.这是一个个人学习项目，仅是为了联系flutter，star才500+
2.我愿意听取阿里云盘官方的任何建议和要求
3.当前我对阿里云盘并没有什么实质性的建议，他已经完全满足了我的所有需求--存储、下载（是的，我并不怎么上传）。虽然我开发了这个小程序，但是我也在使用官方的客户端，当前的阿里云盘PC客户端的功能也已经很完善，我并没有意识还有什么需要规划的功能。

提一些小建议吧：（说的是官方桌面版）
1.相册、保险箱还是早日开放吧，手机备份了照片，电脑端却不能操作

2.传输列表里，默认显示上传列表，我认为大家还是下载多，上传少，应该默认显示下载列表。每次我都要点2下（点传输列表，点下载列表）

3.文件里，当点击选中一个文件夹后，底部黑色悬浮菜单条，太窄了，有个更多按钮，点一下更多按钮只显示“移动”。这就很多余了，直接显示移动不好吗？

4.文件里，当前阿里云盘并未对文件名做任何限制，所以可以创建一些带有特殊符号的文件名(/\*?)，这些特殊符号导致在windows上无法正确下载

5.当前下载速度似乎并不能满速下载，早期我经常遇到单文件只有2-3MB/s的下载速度，也是我开发小白羊的原因，想下的快一点。现在最新版基本很轻松就19MB/s，但是我的宽带是30MB/s满速，所以似乎还可以优化一下


就这么多了，都是小细节，并没有什么实质的建议，共进共勉,祝顺商祺

**Comment by liupan1890** [comment]
I'm very sorry, my English is not good

1. This is a personal learning project. It's just for contacting flitter. Star is only 500+

2. I am willing to listen to any suggestions and requests from Alibaba cloud disk

3. At present, I don't have any substantive suggestions on Alibaba cloud disk. It has fully met all my needs - storage and download (yes, I don't upload much). Although I have developed this small program, I am also using the official client. The functions of the current alicloud disk PC client are perfect. I don't know what other functions need to be planned.

Make some suggestions: (it's the official desktop version)

1. The photo album and safe should be opened as soon as possible. The mobile phone has backed up the photos, but the computer can't operate them

2. In the transmission list, the upload list is displayed by default. In my opinion, we should display the download list by default because there are more downloads and less uploads. Every time I order 2 times (click transmission list, click download list)

3. In the file, when you click to select a folder, the black floating menu bar at the bottom is too narrow. There is a more button. Click the more button to display "move". This is more than a lot, direct display mobile is not good?

4. In the file, the current alicloud disk does not impose any restrictions on the file name, so you can create some file names with special symbols (/ \ *?), These special symbols cannot be downloaded correctly on windows

5. It seems that the current download speed is not full speed. In the early days, I often encountered a single file download speed of only 2-3mb / s, which is also the reason why I developed little Aries. I want to make it faster. Now the latest version is basically very easy, 19Mb / s, but my broadband is 30MB / s full speed, so it seems that I can optimize it

**Comment by liupan1890** [comment]
补充2点：
1.当前的在线解压缩功能很不完善，第一：点击解压后需要等很久才能解压完（我测试的都是10MB的压缩包）第二：多次解压无密码的zip文件都失败了

2.当前阿里云盘缺少复制功能，如果需要把一个文件，保存到不同的2个文件夹里面，就需要上传2次，而不能只上传1次然后点击复制按钮复制一份到另外的文件夹。这个感觉再分享文件时，在整理文件时，都需要用到复制功能。现在只有移动功能没有复制功能

**Comment by liupan1890** [comment]
Two additional points:

1. The current online decompression function is not perfect. First, it takes a long time to complete the decompression after clicking decompression (all the packages I tested are 10MB). Second, it fails to decompress the zip file without password for many times

2. Currently, alicloud disk lacks the copy function. If you need to save a file to two different folders, you need to upload it twice instead of just once, and then click the copy button to copy it to another folder. When sharing files, you need to use the copy function when organizing files. Now there is only move function, no copy function

I'm glad to have the opportunity to communicate with the government. I won't close this issue. If other people see any suggestions, please reply

**Comment by skorver** [comment]
> 十分抱歉，我的英语并不好
> 1.这是一个个人学习项目，仅是为了联系flutter，star才500+
> 2.我愿意听取阿里云盘官方的任何建议和要求
> 3.当前我对阿里云盘并没有什么实质性的建议，他已经完全满足了我的所有需求--存储、下载（是的，我并不怎么上传）。虽然我开发了这个小程序，但是我也在使用官方的客户端，当前的阿里云盘PC客户端的功能也已经很完善，我并没有意识还有什么需要规划的功能。
> 
> 提一些小建议吧：（说的是官方桌面版）
> 1.相册、保险箱还是早日开放吧，手机备份了照片，电脑端却不能操作
> 
> 2.传输列表里，默认显示上传列表，我认为大家还是下载多，上传少，应该默认显示下载列表。每次我都要点2下（点传输列表，点下载列表）
> 
> 3.文件里，当点击选中一个文件夹后，底部黑色悬浮菜单条，太窄了，有个更多按钮，点一下更多按钮只显示“移动”。这就很多余了，直接显示移动不好吗？
> 
> 4.文件里，当前阿里云盘并未对文件名做任何限制，所以可以创建一些带有特殊符号的文件名(/*?)，这些特殊符号导致在windows上无法正确下载
> 
> 5.当前下载速度似乎并不能满速下载，早期我经常遇到单文件只有2-3MB/s的下载速度，也是我开发小白羊的原因，想下的快一点。现在最新版基本很轻松就19MB/s，但是我的宽带是30MB/s满速，所以似乎还可以优化一下
> 
> 就这么多了，都是小细节，并没有什么实质的建议，共进共勉,祝顺商祺

非常感谢，因为不少问题和版本的存续，都想和您后续直接有些讨论，我们方便微信认识一下吗？ 我叫衣鹏，负责云盘的公众沟通。我的微信是korver24

**Comment by omy2000** [comment]
大佬有人来招安了

**Comment by liupan1890** [comment]
你太客气了，其实我就是个人兼职开发，并没有什么多好的技术，小白羊的功能上也是我用到什么了就添上，纯粹是靠时间堆砌出来的，毕竟是个人经验有限，所以如果有哪里做的不合适的，你就直接跟我说就行，不用太客气，因为我也没有啥规划。我也不认为我能给阿里团队提什么有用的建议，沟通上还是以github为主，我基本每天都会上来回复的。其实我前几个月还一直在跑美团，实在太累了所以才回来做程序。。。。也是挺丢人的。。。
也希望其他人也都群策群力，有啥建议也都回复在这个帖子里，能直接和官方沟通也挺好，其实我知道大家也就是临时过渡，最终还是靠官方的

**Comment by liupan1890** [comment]
@omy2000 你就想多了，野生怪怎么能被招安。。。。阿里入职都不知道要有几轮背调了，我到是真想被招安，人家是公众沟通好不啦

**Comment by skorver** [comment]
> @skorver 你太客气了，其实我就是个人兼职开发，并没有什么多好的技术，小白羊的功能上也是我用到什么了就添上，纯粹是靠时间堆砌出来的，毕竟是个人经验有限，所以如果有哪里做的不合适的，你就直接跟我说就行，不用太客气，因为我也没有啥规划。我也不认为我能给阿里团队提什么有用的建议，沟通上还是以github为主，我基本每天都会上来回复的。其实我前几个月还一直在跑美团，实在太累了所以才回来做程序。。。。也是挺丢人的。。。
> 
> 也希望其他人也都群策群力，有啥建议也都回复在这个帖子里，能直接和官方沟通也挺好，其实我知道大家也就是临时过渡，最终还是靠官方的

😂我们不是要把您官方化，相反有些面向开发者的接口，您有兴趣可以帮更多试试看；但是在这里没法发这种测试阶段的文档嘛。或者我们电邮做点沟通可以吗？

**Comment by skorver** [comment]
> 大佬有人来招安了
> 
> 

欢迎一起玩出自己的云盘～～

**Comment by liupan1890** [comment]
收到，我已经向您的邮箱发送了邮件，期待
